name: Code Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17 (Adoptium)
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Configura Java 17 aquí
          distribution: 'temurin'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          sonar-project-key: your-sonar-project-key  # Tu clave de proyecto aquí
          sonar-host-url: 'https://sonarcloud.io'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
