name: Terraform Security Scan with Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Trivy
      run: |
        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.29.1/trivy_0.29.1_Linux-64bit.tar.gz -o trivy.tar.gz
        tar xzf trivy.tar.gz
        sudo mv trivy /usr/local/bin/

    - name: Run Trivy scan on Terraform code
      run: |
        trivy fs --format json --output trivy-report.json .

    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v3
      with:
        name: trivy-scan-results
        path: trivy-report.json
