name: "Security Scan with Trivy"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Run Trivy scan
      run: |
        trivy image --format json --output trivy-report.json <image_name>

    - name: List files
      run: ls -la  # Esto ayudará a verificar si el archivo está presente

    - name: Upload Trivy scan results as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-results
        path: trivy-report.json